import { describe, expect, test } from "bun:test";
import { BunServices } from "@effect/platform-bun";
import { Effect } from "effect";
import { checkLinguistGenerated, classifyFile } from "../src/classify.ts";
import { cleanupTestRepo, makeTestRepo } from "./fixtures.ts";

describe("classifyFile", () => {
	test("classifies a plain source file as implementation", () => {
		expect(
			classifyFile({ path: "src/widget.ts", linguistGenerated: false }),
		).toBe("implementation");
	});

	test("classifies test files by Jest/Vitest naming conventions", () => {
		expect(
			classifyFile({ path: "src/widget.test.ts", linguistGenerated: false }),
		).toBe("test");
		expect(
			classifyFile({ path: "src/widget.spec.tsx", linguistGenerated: false }),
		).toBe("test");
		expect(
			classifyFile({
				path: "src/__tests__/widget.ts",
				linguistGenerated: false,
			}),
		).toBe("test");
	});

	test("classifies lockfiles as generated regardless of extension", () => {
		expect(classifyFile({ path: "bun.lock", linguistGenerated: false })).toBe(
			"generated",
		);
		expect(
			classifyFile({
				path: "packages/app/package-lock.json",
				linguistGenerated: false,
			}),
		).toBe("generated");
	});

	test("classifies minified and sourcemap files as generated", () => {
		expect(
			classifyFile({ path: "dist/app.min.js", linguistGenerated: false }),
		).toBe("generated");
		expect(
			classifyFile({ path: "dist/app.js.map", linguistGenerated: false }),
		).toBe("generated");
	});

	test("classifies files carrying a generated content marker", () => {
		expect(
			classifyFile({
				path: "gen/api.ts",
				linguistGenerated: false,
				contentPrefix: "// Code generated by protoc-gen-ts. DO NOT EDIT.\n",
			}),
		).toBe("generated");
		expect(
			classifyFile({
				path: "gen/api.ts",
				linguistGenerated: false,
				contentPrefix: "// @generated by some tool\n",
			}),
		).toBe("generated");
	});

	test("linguist-generated attribute wins even without a filename or content signal", () => {
		expect(
			classifyFile({
				path: "src/handwritten-looking.ts",
				linguistGenerated: true,
				contentPrefix: "export const x = 1;\n",
			}),
		).toBe("generated");
	});

	test("generated takes precedence over a test-looking filename", () => {
		expect(
			classifyFile({
				path: "__snapshots__/widget.test.min.js",
				linguistGenerated: false,
			}),
		).toBe("generated");
	});

	test("plain prose mentioning 'generated' without the @generated marker stays implementation", () => {
		expect(
			classifyFile({
				path: "src/widget.ts",
				linguistGenerated: false,
				contentPrefix: "// this file was generated by hand, not a tool\n",
			}),
		).toBe("implementation");
	});
});

describe("checkLinguistGenerated", () => {
	test("reports paths marked linguist-generated via .gitattributes", async () => {
		const repo = await makeTestRepo();
		try {
			await repo.write(".gitattributes", "vendor/** linguist-generated\n");
			await repo.write("vendor/thing.ts", "// vendored\n");
			await repo.write("src/hand.ts", "export const x = 1;\n");
			await repo.commit("initial");

			const generated = await Effect.runPromise(
				checkLinguistGenerated(repo.root, [
					"vendor/thing.ts",
					"src/hand.ts",
				]).pipe(Effect.provide(BunServices.layer)),
			);

			expect(generated.has("vendor/thing.ts")).toBe(true);
			expect(generated.has("src/hand.ts")).toBe(false);
		} finally {
			await cleanupTestRepo(repo);
		}
	});

	test("returns an empty set for an empty path list without shelling out", async () => {
		const repo = await makeTestRepo();
		try {
			const generated = await Effect.runPromise(
				checkLinguistGenerated(repo.root, []).pipe(
					Effect.provide(BunServices.layer),
				),
			);
			expect(generated.size).toBe(0);
		} finally {
			await cleanupTestRepo(repo);
		}
	});
});
