// @ts-nocheck
// Auto-generated by review's gen-migrations — do not edit manually

import m0000 from "../drizzle/0000_strange_thor_girl.sql" with { type: "text" };
import journal from "../drizzle/meta/_journal.json" with { type: "json" };

export default {
	journal: journal as {
		entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
	},
	files: {
		"0000_strange_thor_girl": m0000,
	} as Record<string, string>,
};
