// @ts-nocheck
// Auto-generated by settings's gen-migrations — do not edit manually

import m0000 from "../drizzle/0000_massive_prowler.sql" with { type: "text" };
import m0001 from "../drizzle/0001_fluffy_roland_deschain.sql" with {
	type: "text",
};
import m0002 from "../drizzle/0002_damp_quasimodo.sql" with { type: "text" };
import journal from "../drizzle/meta/_journal.json" with { type: "json" };

export default {
	journal: journal as {
		entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
	},
	files: {
		"0000_massive_prowler": m0000,
		"0001_fluffy_roland_deschain": m0001,
		"0002_damp_quasimodo": m0002,
	} as Record<string, string>,
};
