// @ts-nocheck
// Auto-generated by settings's gen-migrations — do not edit manually

import m0000 from "../drizzle/0000_massive_prowler.sql" with { type: "text" };
import m0001 from "../drizzle/0001_fluffy_roland_deschain.sql" with {
	type: "text",
};
import m0002 from "../drizzle/0002_damp_quasimodo.sql" with { type: "text" };
import m0003 from "../drizzle/0003_careful_joseph.sql" with { type: "text" };
import m0004 from "../drizzle/0004_amusing_toad_men.sql" with { type: "text" };
import m0005 from "../drizzle/0005_tan_maggott.sql" with { type: "text" };
import m0006 from "../drizzle/0006_cheerful_captain_america.sql" with {
	type: "text",
};
import m0007 from "../drizzle/0007_late_deadpool.sql" with { type: "text" };
import journal from "../drizzle/meta/_journal.json" with { type: "json" };

export default {
	journal: journal as {
		entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
	},
	files: {
		"0000_massive_prowler": m0000,
		"0001_fluffy_roland_deschain": m0001,
		"0002_damp_quasimodo": m0002,
		"0003_careful_joseph": m0003,
		"0004_amusing_toad_men": m0004,
		"0005_tan_maggott": m0005,
		"0006_cheerful_captain_america": m0006,
		"0007_late_deadpool": m0007,
	} as Record<string, string>,
};
