// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

import m0000 from "../drizzle/20260729023923_massive_prowler/migration.sql" with {
	type: "text",
};
import m0001 from "../drizzle/20260729033420_fluffy_roland_deschain/migration.sql" with {
	type: "text",
};
import m0002 from "../drizzle/20260729103754_damp_quasimodo/migration.sql" with {
	type: "text",
};
import m0003 from "../drizzle/20260730053619_careful_joseph/migration.sql" with {
	type: "text",
};
import m0004 from "../drizzle/20260801054236_amusing_toad_men/migration.sql" with {
	type: "text",
};
import m0005 from "../drizzle/20260802032914_tan_maggott/migration.sql" with {
	type: "text",
};
import m0006 from "../drizzle/20260802040324_cheerful_captain_america/migration.sql" with {
	type: "text",
};
import m0007 from "../drizzle/20260808091904_late_deadpool/migration.sql" with {
	type: "text",
};
import m0008 from "../drizzle/20260825083833_quiet_nick_fury/migration.sql" with {
	type: "text",
};

export default {
	migrations: [
		{ name: "20260729023923_massive_prowler", sql: m0000 },
		{ name: "20260729033420_fluffy_roland_deschain", sql: m0001 },
		{ name: "20260729103754_damp_quasimodo", sql: m0002 },
		{ name: "20260730053619_careful_joseph", sql: m0003 },
		{ name: "20260801054236_amusing_toad_men", sql: m0004 },
		{ name: "20260802032914_tan_maggott", sql: m0005 },
		{ name: "20260802040324_cheerful_captain_america", sql: m0006 },
		{ name: "20260808091904_late_deadpool", sql: m0007 },
		{ name: "20260825083833_quiet_nick_fury", sql: m0008 },
	],
};
