// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

import m0000 from "../drizzle/20260728105416_square_sharon_carter/migration.sql" with {
	type: "text",
};

export default {
	migrations: [{ name: "20260728105416_square_sharon_carter", sql: m0000 }],
};
