#!/usr/bin/env bun
/**
 * Regenerates `.gen/migrations.gen.ts`, embedding `drizzle/`'s journal and
 * SQL files via import attributes so `bun build --compile` bundles them into
 * the sidecar binary instead of leaving them as files it can't find on disk.
 *
 * Run via `bun run db:generate`, after `drizzle-kit generate`. Ported from
 * `@repo/review`'s copy of this same script — small enough (and specific
 * enough to each package's own `drizzle/` layout) that it wasn't worth
 * generalizing into `@repo/db`.
 */
import fs from "node:fs";
import path from "node:path";

const journalPath = path.join(
	process.cwd(),
	"drizzle",
	"meta",
	"_journal.json",
);
const outPath = path.join(process.cwd(), ".gen", "migrations.gen.ts");

const journal = JSON.parse(fs.readFileSync(journalPath, "utf-8")) as {
	entries: Array<{
		idx: number;
		when: number;
		tag: string;
		breakpoints: boolean;
	}>;
};

const imports: Array<string> = [];
const filesEntries: Array<string> = [];

for (const entry of journal.entries) {
	const relSqlPath = path.posix.join("..", "drizzle", `${entry.tag}.sql`);
	const varName = `m${String(entry.idx).padStart(4, "0")}`;
	imports.push(`import ${varName} from "${relSqlPath}" with { type: "text" };`);
	filesEntries.push(`\t"${entry.tag}": ${varName}`);
}

const relJournalPath = path.posix.join(
	"..",
	"drizzle",
	"meta",
	"_journal.json",
);

const content = `// @ts-nocheck
// Auto-generated by walkthrough's gen-migrations — do not edit manually
import journal from "${relJournalPath}" with { type: "json" };
${imports.join("\n")}

export default {
	journal: journal as { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] },
	files: {
${filesEntries.join(",\n")}
	} as Record<string, string>,
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, "utf-8");

// Bring the generated file in line with the repo's biome config (tabs, sorted
// imports, trailing commas) so `check:lint` doesn't flag its own output.
Bun.spawnSync(["bunx", "biome", "check", "--write", outPath], {
	stdout: "inherit",
	stderr: "inherit",
});

console.log(`Generated ${outPath}`);
