/**
 * The zsh completion script for `nisi`, printed verbatim by `nisi completion
 * zsh`. Hand-rolled rather than generated by `effect/unstable/cli`'s zsh
 * generator: the root `nisi` command declares both a positional `path` and
 * subcommands, and that generator emits a spec for each at position 1,
 * producing a "doubled argument definition" that `_arguments -C` aborts on
 * before any completion state is set — nothing ever completes.
 *
 * Refs come straight from `git for-each-ref`, never by shelling out to the
 * `nisi` binary itself — ref listing is pure git and needs none of nisi's
 * own logic. Matches are added with plain `compadd`, not `_describe`/
 * `_values`, so tools like fzf-tab (which render whatever standard compsys
 * produces) see real candidates.
 *
 * Ends with an explicit `compdef _nisi nisi` — a bare `#compdef` header only
 * self-registers a function autoloaded from `$fpath`, not one `eval`'d
 * directly, which is how this script is meant to be installed:
 * `eval "$(nisi completion zsh)"`.
 */
export const zshCompletionScript = `#compdef nisi

_nisi_refs() {
	git for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
}

# Splits $1 the same way base-argument.ts's parseBaseArgument does: a base
# ref, then the first run of 2-3 dots, then whatever's typed of the head ref
# so far. Git forbids ".." inside a single ref name, so the first such run in
# the string can only be the range separator, never part of either ref.
_nisi_complete_base_or_head() {
	local cur=$1 base sep rest
	base=\${cur%%..*}
	rest=\${cur:\${#base}}

	if [[ -z $rest ]]; then
		compadd -- $(_nisi_refs)
		return
	fi

	if [[ $rest == \\.\\.\\.* ]]; then
		sep=...
	else
		sep=..
	fi
	# -P keeps "$base$sep" on the command line: it's inserted before every
	# match rather than replacing what's already typed.
	compadd -P "\${base}\${sep}" -- $(_nisi_refs)
}

_nisi() {
	case \${words[2]} in
		diff)
			case $CURRENT in
				3) _nisi_complete_base_or_head "\${words[3]}" ;;
				4) _files -/ ;;
			esac
			;;
		pr)
			(( CURRENT == 3 )) && _files -/
			;;
		completion)
			(( CURRENT == 3 )) && compadd -- zsh
			;;
		*)
			if (( CURRENT == 2 )); then
				compadd -- pr diff completion
				_files -/
			fi
			;;
	esac
}

compdef _nisi nisi
`;
