// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

import m0000 from "../drizzle/20260902111346_curvy_weapon_omega/migration.sql" with {
	type: "text",
};

export default {
	migrations: [{ name: "20260902111346_curvy_weapon_omega", sql: m0000 }],
};
